#
#  GNUmakefile
#
#  $Id: GNUmakefile,v 1.1 2000/04/03 12:13:48 cdegroot Exp $
#
#  Copyright (C) 2000 Cees de Groot <cg@cdegroot.com>
#
PACKAGE := com.cdegroot.db.hash

MODULES := Test \
	TestExtendibleHashSet \
	TestEntryPage

include ../../../../../../common/Makerules

