#
#  $Id: GNUmakefile,v 1.1 2000/04/03 12:13:48 cdegroot Exp $
#
#  (C)Copyright 1999, 2000 Cees de Groot <cg@cdegroot.com>
#
#  This library is free software; you can redistribute it and/or 
#  modify it under the terms of the GNU Library General Public 
#  License as published by the Free Software Foundation; either 
#  version 2 of the License, or (at your option) any later version.
#
#  This library is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#  Library General Public License for more details.
#
#  You should have received a copy of the GNU Library General Public 
#  License along with this program; if not, write to the Free 
#  Software Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA
#  02111-1307, USA
#  
PACKAGE := com.cdegroot.db.recman

MODULES := \
	Magic BlockView \
	Location \
	PhysicalRowId \
	FreePhysicalRowId \
	FreePhysicalRowIdPage \
	FreePhysicalRowIdPageManager  \
	FreeLogicalRowIdPage \
	FreeLogicalRowIdPageManager \
	TranslationPage \
	RecordHeader \
	BlockIo \
	TransactionManager \
	RecordFile \
	FileHeader \
	PageHeader \
	PageCursor \
	PageManager \
	DataPage \
	PhysicalRowIdManager \
	LogicalRowIdManager \
	RecordManager


include ../../../../../common/Makerules
